# Mihomo Redir-TProxy (MIX) Mode Environment Variables
# TCP REDIRECT + UDP TPROXY hybrid mode

REDIRECT_PORT=22017           # TCP traffic redirect port
TPROXY_PORT=22016             # UDP traffic TProxy port

# Proxy process GID, usually the group ID of the mihomo user
#EXCLUDE_GID=988
ROUTING_MARK=6666
# Firewall mark and routing table ID
FWMARK=1                      # Firewall mark for identifying proxy traffic
TABLE_ID=100                  # Routing table ID for policy routing

# nftables table name
NFTABLES_TABLE=mihomo_redir_tproxy4
